options:
  # Merge default rules
  merge-default-rules: true
files:
  include: 'src/**/*.scss'
rules:
  no-color-keywords: 0
  quotes: 0
  hex-notation: 0
  single-line-per-selector: 0
  property-sort-order:
    - 0 # Disabled, allow any property order
  nesting-depth:
    - 0 # Disabled, allow any nesting depth
  force-element-nesting:
    - 0 # Disables, allows rules like '.container.map'
  no-important:
    - 0 # Disables
  no-qualifying-elements:
    - 0 # Disables
  indentation:
    size: 'tab'
  force-attribute-nesting:
    - 0 # Disables
  no-url-protocols: 
    - 0
  no-url-domains: 
    - 0
  class-name-format:
    - 0
  no-vendor-prefixes:
    - 0
  leading-zero:
    - 2
    -
      include: true
